version: '3'

name: chart

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 6379:6379

  mysql:
    image: mysql:latest
    container_name: mysql
    platform: linux/arm64  #
    environment:
     MYSQL_ROOT_PASSWORD: 123456789  
     MYSQL_DATABASE: chartchart  
     MYSQL_USER: dev
     MYSQL_PASSWORD: 123456789  
     LC_ALL : C.UTF-8
    ports:
      - "3306:3306"  
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/mysql.conf.d/mysql.cnf:ro  #
volumes:
  mysql:
